### PR TITLE
Fix the sequence diagrams

### PR DESCRIPTION
**Pull request by snorp**

### CODE REVIEW

**Comment by snorp** [comment]
There is a regression in svgcheck that seems to break svg generation. You may also need the following change in `lib/` to make things build.

```
diff --git a/requirements.txt b/requirements.txt
index a1c530a..e77476b 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -3,6 +3,6 @@ iddiff
 pyang
 pyyaml
 rfc-tidy
-svgcheck
+svgcheck == 0.6.2
 toml
 xml2rfc
```

**Review by dimmyvi — APPROVED** [review]

**Comment by snorp** [comment]
Yup, need that Makefile fix as well, but I guess I need to figure out the `svgcheck` issue. Downgrading it made things work for me here, but I can't make it break again by installing `0.7.1`, so now I'm wondering if it's some dependency of `svgcheck` that's actually causing the problem.

**Comment by dimmyvi** [comment]
svgcheck manual version fix works for local build, but github auto build fails. I can try manually publish the doc with fixed diagrams.

**Comment by snorp** [comment]
There's a workaround in the latest `kramdown-rfc` (https://github.com/cabo/kramdown-rfc/issues/187) so things might be fine if we just rekick the jobs.

**Comment by dimmyvi** [comment]
@snorp, applied chnages from this PR inhttps://github.com/dimmyvi/tigress-requirements/pull/47 - due to failing checks here. #47 merged successsfully.

**Pull request closed without merging**
